spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8888 # URL do Config Server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false # Serwer nie rejestruje się w innym serwerze
    fetchRegistry: false
  server:
    enableSelfPreservation: false # Opcjonalnie wyłącz auto-ochronę
