spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: resource-server
          uri: lb://RESOURCE-SERVER
          predicates:
            - Path=/api/resource/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://login.microsoftonline.com/daabb5ae-8e62-4b23-9856-e92092b5d08f/v2.0


management:
  endpoints:
    web:
      exposure:
        include: '*'
